parc:
    resource: "@ParcBundle/Resources/config/routing.yml"
    prefix:   /

tek_up_etudiant:
    resource: "@TekUpEtudiantBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
